//
//  EntryListWorker.swift
//  MobileDataUsage
//
//  Created by cdgtaxiMac on 3/24/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import CoreData

protocol EntryListStoreProtocol: class
{
    func doSomeWork()
}

class EntryListWorker
{
    var entryListStoreProtocol: EntryListStoreProtocol
    
    init(entryListStoreProtocol: EntryListStoreProtocol)
    {
        self.entryListStoreProtocol = entryListStoreProtocol
    }
    
    func doSomeWork()
    {
    }
}
