//
//  EntryListInteractor.swift
//  MobileDataUsage
//
//  Created by cdgtaxiMac on 3/24/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EntryListBusinessLogic {
    func getEntryData()
}

protocol EntryListDataStore {
    
}

class EntryListInteractor: EntryListBusinessLogic, EntryListDataStore {
    var presenter: EntryListPresentationLogic?
    var worker: EntryListWorker?
    
    func getEntryData() {
        worker = EntryListWorker(entryListStoreProtocol: EntryListAPIStore())
        worker?.getEntryData(completion: { [weak self] (entryListData) in
            self?.presenter?.presentEntryList(response: entryListData)
        })
    }
}
