//
//  EntryListInteractor.swift
//  MobileDataUsage
//
//  Created by cdgtaxiMac on 3/24/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EntryListBusinessLogic
{
    func doSomething(request: EntryListModel.Request)
}

protocol EntryListDataStore
{
    
}

class EntryListInteractor: EntryListBusinessLogic, EntryListDataStore
{
    var presenter: EntryListPresentationLogic?
    var worker: EntryListWorker?
    
    func doSomething(request: EntryListModel.Request)
    {
        worker = EntryListWorker(entryListStoreProtocol: EntryListAPIStore())
        worker?.doSomeWork()
        
        let response = EntryListModel.Response()
        presenter?.presentSomething(response: response)
    }
}
