//
//  EntryListViewController.swift
//  MobileDataUsage
//
//  Created by cdgtaxiMac on 3/24/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EntryListDisplayLogic: class {
    func displaySomething(viewModel: EntryListModel.ViewModel)
}

class EntryListViewController: UIViewController, EntryListDisplayLogic, EntryListViewProtocol {
    var interactor: EntryListBusinessLogic?
    var router: (NSObjectProtocol & EntryListRoutingLogic & EntryListDataPassing)?
    
    lazy var myView: EntryListView = {
        let view = EntryListView()
        view.delegate = self
        view.dataUsageTable.delegate = self
        view.dataUsageTable.dataSource = self
        view.backgroundColor = .systemGray6
        view.translatesAutoresizingMaskIntoConstraints = false
        return view
    }()
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = EntryListInteractor()
        let presenter = EntryListPresenter()
        let router = EntryListRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    private func setupView() {
        edgesForExtendedLayout = []
        navigationController?.navigationBar.backgroundColor = .systemGray
        view.addSubview(myView)
        view.addConstraint(NSLayoutConstraint(
            item: myView,
            attribute: .top,
            relatedBy: .equal,
            toItem: view,
            attribute: .top,
            multiplier: 1,
            constant: 0))
        view.addConstraint(NSLayoutConstraint(
            item: myView,
            attribute: .bottom,
            relatedBy: .equal,
            toItem: view,
            attribute: .bottom,
            multiplier: 1,
            constant: 0))
        view.addConstraint(NSLayoutConstraint(
            item: myView,
            attribute: .trailing,
            relatedBy: .equal,
            toItem: view,
            attribute: .trailing,
            multiplier: 1,
            constant: 0))
        view.addConstraint(NSLayoutConstraint(
            item: myView,
            attribute: .width,
            relatedBy: .equal,
            toItem: view,
            attribute: .width,
            multiplier: 1,
            constant: 0))
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setup()
        setupView()
        doSomething()
    }
    
    // MARK: Event Handling
    
    func doSomething() {
        let request = EntryListModel.Request()
        interactor?.doSomething(request: request)
    }
    
    // MARK: Display Handling
    
    func displaySomething(viewModel: EntryListModel.ViewModel) {
        
    }
}

extension EntryListViewController: UITableViewDelegate, UITableViewDataSource {
    
    func numberOfSections(in tableView: UITableView) -> Int {
        return 12
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 1
    }

    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: myView.cellID, for: indexPath) as! EntryListCell
        cell.textLbl.text = "Hello World"
        cell.selectionStyle = .none
        return cell
    }
    
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return 50.0
    }
    
    

}
