//
//  EntryListRouter.swift
//  MobileDataUsage
//
//  Created by cdgtaxiMac on 3/24/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol EntryListRoutingLogic
{
    func navigateToSomewhere(source: EntryListViewController, destination: UIViewController)
}

protocol EntryListDataPassing
{
    var dataStore: EntryListDataStore? { get }
}

class EntryListRouter: NSObject, EntryListRoutingLogic, EntryListDataPassing
{
    weak var viewController: EntryListViewController?
    var dataStore: EntryListDataStore?
    
    // MARK: Navigation
    
    func navigateToSomewhere(source: EntryListViewController, destination: UIViewController)
    {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    //func passDataToSomewhere(source: EntryListDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
