//
//  EntryListPresenter.swift
//  MobileDataUsage
//
//  Created by cdgtaxiMac on 3/24/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EntryListPresentationLogic
{
    func presentSomething(response: EntryListModel.Response)
}

class EntryListPresenter: EntryListPresentationLogic
{
    weak var viewController: EntryListDisplayLogic?
    
    func presentSomething(response: EntryListModel.Response)
    {
        let viewModel = EntryListModel.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
