//
//  EntryListPresenter.swift
//  MobileDataUsage
//
//  Created by cdgtaxiMac on 3/24/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EntryListPresentationLogic
{
    func presentEntryList(response: EntryListModel.Response.EntryList?)
}

class EntryListPresenter: EntryListPresentationLogic
{
    weak var viewController: EntryListDisplayLogic?
    
    func presentEntryList(response: EntryListModel.Response.EntryList?)
    {
        guard let success = response?.success else { return }
        if !success {
            viewController?.displayError(errorMsg: "Request not successful. Please Try Again.")
        } else {
            let viewModel = EntryListModel.ViewModel(entryListDataResponse: response)
            viewController?.displayEntryList(viewModel: viewModel)
        }
        
    }
}
