//
//  EntryListInteractor.swift
//  MobileDataUsage
//
//  Created by cdgtaxiMac on 3/24/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EntryListBusinessLogic {
    func getEntryData()
    func getCachedEntryData()
}

protocol EntryListDataStore {
    
}

class EntryListInteractor: EntryListBusinessLogic, EntryListDataStore {
    var presenter: EntryListPresentationLogic?
    var worker = EntryListWorker(entryListStoreProtocol: EntryListAPIStore())
    
    func getEntryData() {
        worker.getEntryData(completion: { [weak self] (entryListData) in
            self?.presenter?.presentEntryList(response: entryListData)
        })
    }
    
    func getCachedEntryData() {
        // display cache before requesting a new one
        if let cachedEntryData = Tool.shared.getFile() {
            do {
                let decoder = JSONDecoder()
                let cachedData = try decoder.decode(EntryListModel.Response.EntryList.self, from: cachedEntryData)
                self.presenter?.presentEntryList(response: cachedData)
            } catch {
                print(error)
            }
        }
    }
}
