//
//  EntryListWorker.swift
//  MobileDataUsage
//
//  Created by cdgtaxiMac on 3/24/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import CoreData

protocol EntryListStoreProtocol: class {
    func getEntryData(completion: @escaping(EntryListModel.Response.EntryList?) -> Void)
}

class EntryListWorker {
    var entryListStore: EntryListStoreProtocol
    
    init(entryListStoreProtocol: EntryListStoreProtocol) {
        self.entryListStore = entryListStoreProtocol
    }
    
    func getEntryData(completion: @escaping(EntryListModel.Response.EntryList?) -> Void) {
        entryListStore.getEntryData { (entryListData) in
            completion(entryListData)
        }
    }
}
